infinispan1: 
  image: jboss/infinispan-server:9.0.0.Final
  container_name: ispn-1
infinispan2:
  image: jboss/infinispan-server:9.0.0.Final
  container_name: ispn-2
sparkMaster:
  image: gustavonalle/spark:2.1.0
  container_name: sparkMaster
  volumes:
    - $PWD/target:/usr/local/code
sparkSlave:
  image: gustavonalle/spark:2.1.0
  container_name: sparkSlave
  links:
    - sparkMaster:master
